### ISSUE TITLE
Can I work with Azure free tier?

### ISSUE THREAD

**Issue by asashiho** [UiPath/Infrastructure#1]
Hi!

I want to deploy UiPath orchestrator using Azure Marketplace/Azure free tier.
But I have the same problem.
[https://stackoverflow.com/questions/56801051/no-default-service-level-objective-found-of-edition-generalpurpose-while-deplo](https://stackoverflow.com/questions/56801051/no-default-service-level-objective-found-of-edition-generalpurpose-while-deplo)

Can I work with Azure free tier?

**Comment by hteo1337** [comment]
Hi, unfortunately you can't work with Azure free tier. You can modify the service plan to the lowest level, but not the free one.
