### ISSUE TITLE
AWS with-VPC CF template orchestrator login failing and reset pw not working - think we need SES running

### ISSUE THREAD

**Issue by obriensystems** [UiPath/Infrastructure#113]
**Describe the bug**
AWS with-VPC CF template orchestrator login failing and reset pw not working - think we need SES running

**Product and Cloud**
latest CF template with-vpc here - 2 regions
https://aws-quickstart.github.io/quickstart-uipath-orchestrator/#_launch_the_quick_start

**Expected behavior**
login works or the reset password works

**Additional context**
screen cap
<img width="441" alt="Screen Shot 2021-04-23 at 11 26 16" src="https://user-images.githubusercontent.com/24765473/115894430-44ce9080-a427-11eb-8492-c6d3077dd39e.png">
Invalid credentials (#MTI_7)
<img width="1385" alt="Screen Shot 2021-04-23 at 11 31 08" src="https://user-images.githubusercontent.com/24765473/115894589-70ea1180-a427-11eb-9a9d-82017e279f46.png">

**Comment by obriensystems** [comment]
I tried 2 different deployments on us-east-2 and us-east-1 to make sure the PW was exact - note we are constrained to an email username by the cloudformation template

**Comment by AndreiBarbuOz** [comment]
please use the password for the host tenant, with username `admin`

**Comment by obriensystems** [comment]
I was using the HA username - my bad
