### ISSUE TITLE
Won't install studio even set the robot type with "developmemt" or "Nonproduction"

### ISSUE THREAD

**Issue by aaron-h** [UiPath/Infrastructure#24]
Line 97 of Infrastructure/Setup/Install-UiRobot.ps1:
  _**if ($RobotType -eq "Unattended" -or "Attended" )**_  will always value true, so it will never to go else block even RobotType is "developmemt" or "Nonproduction"

**Comment by AndreiBarbuOz** [comment]
Please provide more details
