### ISSUE TITLE
Robot fails to connect with orchestrator after recent change.

### ISSUE THREAD

**Issue by JD2091** [UiPath/Infrastructure#36]
Robot now fails to connect to connect to orchestrator after recent change. I have been using the script in my ARM template since long but have started facing this issue recently. 

It always logs that robot already exist when there is no such robot connected to orchestator and then it fails to connect with orchestrator.

![image](https://user-images.githubusercontent.com/59189591/80446789-6a6cab00-8935-11ea-9a87-d73662b74d11.png)

As seen from tray it is understood that it fails to connect with orchestrator.

![image](https://user-images.githubusercontent.com/59189591/80447036-f7afff80-8935-11ea-81c3-c16ae6872910.png)

**Comment by ubikusss** [comment]
Even if you get that error, it still tries to connect the robot to the orchestrator. 

Does it work if you manually connect it to the Orchestrator?

**Comment by JD2091** [comment]
Yes manually if i try to connect to orchestrator, it connects correctly.

**Comment by ubikusss** [comment]
Ok, let me investigate this, what is the orchestrator version you are attaching the robot to?

**Comment by JD2091** [comment]
Version 19.10.15

**Comment by JD2091** [comment]
@ubikusss any update on this ?

**Comment by ubikusss** [comment]
Not yet, sorry!

**Comment by JD2091** [comment]
Is there any way I can point my ARM template to use the older version ? If yes pleasee let me know how to achieve the same..

**Comment by ubikusss** [comment]
You can just go to history:
https://github.com/UiPath/Infrastructure/commits/master/Setup/Install-UiRobot.ps1
And then click on the browse button on commit that you want:
![image](https://user-images.githubusercontent.com/10058111/81374871-eb336000-9108-11ea-8ffc-e2cd56ab5664.png)

**Comment by JD2091** [comment]
@ubikusss I was just checking with previous versions as you mentioned but unfortunately I am getting same error. That brought me to few more questions. Please try to answer if you are aware about the same.

- In order to authenticate on orchestrator script is using ` $orchestratorUrl/account/login` while orchestrator guide shows `$orchestratorUrl/api/account/authenticate` . Is it correct ?
- Authentication message does show `success = true` but does not return authorization token `result = ` is blank when i try to use ` $orchestratorUrl/account/login` for authenticating. Is this correct behavior ?
- Even if i continue with this it says Error 400 : Bad request while trying to `Invoke-RestMethod -Uri $orch_bot -Method Post -Body $dataRobot -ContentType "application/json" -WebSession $websession -UseBasicParsing` . How to resolve this ?

Actually i thought to have a working script keeping this ones as base and ARM template to always call this newly created working script. But I am not able to proceed further due to above issues.

Please help on this or suggest appropriate place/person for such questions.

**Comment by ubikusss** [comment]
Thank you for testing this. We will have some updates on the scripts. Still to unblock you now here are some answers for your questions:

/account/login is an older method of authentication and we were switching to account/authenticate anyways in the upcoming updates. You can use the following snippet to create a websession that you will use onward in your API calls. Can you please try this out and let me know if everything is ok?


      $orchUrl_login = "$orchestratorUrl/api/Account/Authenticate"

      # login API call to get the login session used for all requests
      $orchWebResponse = Invoke-RestMethod -Uri $orchUrl_login -Method Post -Body $dataLogin -ContentType "application/json" -UseBasicParsing -Session websession
      $websession.Headers.Add('Authorization', "Bearer " + $orchWebResponse.result)
      # log log log
      if ($sDebug) {
        Log-Write -LogPath $sLogFile -LineValue "Logging Orchestrator Web Response"
        Log-Write -LogPath $sLogFile -LineValue $orchWebResponse
      }

**Comment by JD2091** [comment]
@ubikusss Thanks i will try and let you know.

**Comment by JD2091** [comment]
It seems working but sometimes I get error `Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host` . Adding ` -DisableKeepAlive` solves the issue. I am not sure if its required in this script as it can only be who is facing this issue.

I am not able to create Bots with type "Nonproduction". i am getting error as below.
![image](https://user-images.githubusercontent.com/59189591/81560484-1c34be80-93af-11ea-995f-090f1f78a16d.png)

Please help getting rid of this one.

**Comment by ubikusss** [comment]
Off the top of my head, could you try to use "NonProduction" (PascalCase).

**Comment by JD2091** [comment]
That worked :P How could i miss such a silly thing and try lot many other things that had nothing to do with :(
