### ISSUE TITLE
Terraform option for Azure

### ISSUE THREAD

**Issue by Koxzi95** [UiPath/Infrastructure#48]
Hi there, 

It would be great to see a terraform option for Azure as well with VM + Azure SQL. 
Shows an equivalent to AWS where an App Service isn't to be used.

**Comment by ubikusss** [comment]
Hey, thanks for the suggestion!
We're currently preparing an Azure VM deployment via ARM templates for Azure and on a longer term we are also thinking of adding terraform deployments.

**Comment by Koxzi95** [comment]
That's great to hear. 
Either way works fine for most organisations. 
Sorry to add a query into the thread but will this support the latest orchestrator version @ubikusss

**Comment by ubikusss** [comment]
The first update (for ARM templates) will support 19.10.18. 
Next we will be working on adding 20.4 to ARM.

**Comment by Koxzi95** [comment]
Great thank you. I can feed this back to our dev team. 👍
