### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure on script run

### ISSUE THREAD

**Issue by Koxzi95** [UiPath/Infrastructure#53]
When running the latest version of [Install-UiPathOrchestrator.ps1](https://github.com/UiPath/Infrastructure/blob/master/Setup/Install-UiPathOrchestrator.ps1) on a new AWS EC2 instance connecting to EC2 SQL server 2019 we are receiving HTTP Error 500.30 - ANCM In-Process Start Failure and multiple redirects. 

<img width="482" alt="new-install-issue" src="https://user-images.githubusercontent.com/6239399/87877667-78334900-c9d7-11ea-8de2-a61bb74fab9d.png">

**Comment by ubikusss** [comment]
This might be a configuration issue or faulted hosting bundle. This link might be able to help fix the issue manually:
https://docs.uipath.com/orchestrator/lang-zh_CN/docs/identity-server-troubleshooting

**Comment by AndreiBarbuOz** [comment]
please reopen if issue reappears
