### ISSUE TITLE
Facing issue while installing Orchestrator , rewrite module is not downloading for IIS

### ISSUE THREAD

**Issue by mkumarroy1991** [UiPath/Infrastructure#57]
Orchestrator installation failed as IIS rewrite module is not downloading.

**Comment by mattdjames** [comment]
I had this issue and it seems Microsoft changed the URL. I used 
        #$source += "https://download.microsoft.com/download/1/2/8/128E2E22-C1B9-44A4-BE2A-5859ED1D4592/rewrite_amd64_en-US.msi"

**Comment by ubikusss** [comment]
I think the URL was already changed in this repo. @mkumarroy1991 , can you please confirm?

**Comment by AndreiBarbuOz** [comment]
please reopen if the issue reappears
