### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by mattdjames** [UiPath/Infrastructure#59]
I have been installing Orchestrater silently and it works well apart from I couldn't get the pre requisites to install and was getting .Net Framework 4.7.2 failed. So I created a custom AMI in AWS with them pre installed. I can install Orchestrator with self signed certificate and use computer name but I want to use my own public URL and third party certificate. How can this be automated?

I have tried removing the creation of the self signed cert and importing the SSL cert I want to use into local machine personal store first and referencing the thumbprint. I have also added to additional MSI properties for Public URL and certificate subject. Using the Ui Path Orchestrator command line reference guide. However the MSI fails to install using the install script.

Any help would be appreciated.

  $msiProperties += @{
        "ORCHESTRATORFOLDER"          = "`"$($orchestratorFolder)`"";
        "DB_SERVER_NAME"              = "$($databaseServerName)";
        "DB_DATABASE_NAME"            = "$($databaseName)";
        "CERTIFICATE_SUBJECT"         = "$(*.myurl.com)";
    #    "WEBSITE_NAME"                = "$(UiPath Orchestrator)";
		"HOSTADMIN_PASSWORD"          = "$($orchestratorAdminPassword)";
        "DEFAULTTENANTADMIN_PASSWORD" = "$($orchestratorAdminPassword)";										
        "APP_ENCRYPTION_KEY"          = "$($getEncryptionKey.encryptionKey)";
        "APP_NUGET_ACTIVITIES_KEY"    = "$($getEncryptionKey.nugetKey)";
        "APP_NUGET_PACKAGES_KEY"      = "$($getEncryptionKey.nugetKey)";
        "APP_MACHINE_DECRYPTION_KEY"  = "$($getEncryptionKey.DecryptionKey)";
        "APP_MACHINE_VALIDATION_KEY"  = "$($getEncryptionKey.Validationkey)";
        "TELEMETRY_ENABLED"           = "0";
        "PUBLIC_URL"                  = "$($orchestratorHostname)";

I have added the parameter -OrchestratorHostname

thanks

Matt

**Comment by ubikusss** [comment]
Thank you for your feedback and being a product user 😄 
I would first test this out on a machine with logging enabled. See below link for reference:
[https://docs.uipath.com/installation-and-upgrade/docs/orchestrator-command-line-parameters ](url)
The log should have more details on why it failed.

Did you check to see if the certificate requirements are met?
See: [https://docs.uipath.com/installation-and-upgrade/docs/orchestrator-is-prerequisites-for-installation](url)
And maybe most importantly what version did you try to install?

**Comment by mattdjames** [comment]
Hi, thanks for replying 😊 I can install using the certificate using the GUI. But need to automate and install silently. The install fails and doesn’t install the website. Version 20.4.1 is the version I am trying to install.

Logging is enabled.

Kind Regards
Matt James
Senior Consultant | Consulting | Deloitte LLP
D: +44 1293 76 1328 | M: +44 7787 748593
mjames@deloitte.co.uk<mailto:mjames@deloitte.co.uk> | www.deloitte.co.uk

**Comment by ubikusss** [comment]
Ok, understood. Still, for now we do not support the 20.4 version on this github repo. This is maintained best-effort and changes here are not on the short roadmap. There are some changes like the addition of identity server that need to be taken into consideration for this installation. 

Also I would suggest using the 20.4.3 version.

**Comment by mattdjames** [comment]
Ok thanks for the info, I will try the previous version and let you know.

thanks

Kind Regards
Matt James
Senior Consultant | Consulting | Deloitte LLP
D: +44 1293 76 1328 | M: +44 7787 748593
mjames@deloitte.co.uk<mailto:mjames@deloitte.co.uk> | www.deloitte.co.uk

**Comment by AndreiBarbuOz** [comment]
please reopen if issue reappears
