### ISSUE TITLE
Validation error for existing passwords

### ISSUE THREAD

**Issue by vicki075** [UiPath/Infrastructure#69]
While passing the parameters for database, it is validating the password. The password is pre-existing and this should not be validated.
![image](https://user-images.githubusercontent.com/46535090/100487847-b7fe0000-3130-11eb-8a8f-aa51dd6e2ba4.png)

**Comment by ubikusss** [comment]
Where is this specifically?

**Comment by vicki075** [comment]
While deploying orchestrator from marketplace on an existing DB

**Comment by ubikusss** [comment]
At this point there is no option to deploy the Orchestrator using an existing Database in the azure marketplace. A new SQL DB will be created for you.
